from enum import Enum

class WorkflowStage(str, Enum):
    INITIALIZED = "INITIALIZED"
    IDEA_ANALYSIS = "IDEA_ANALYSIS"
    MARKET_RESEARCH = "MARKET_RESEARCH"
    CRITIC_VALIDATION = "CRITIC_VALIDATION"
    REPLANNING = "REPLANNING"
    BUSINESS_MODEL = "BUSINESS_MODEL"
    REVENUE_ESTIMATION = "REVENUE_ESTIMATION"
    MARKETING = "MARKETING"
    ROADMAP_COMPILATION = "ROADMAP_COMPILATION"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
